<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // ORDINATEURS PORTABLES (10)
            [
                'nom' => 'Dell XPS 13 Plus',
                'category' => 'laptop',
                'description' => 'Ultra-slim laptop with InfinityEdge display, Intel Core i7, 16GB RAM, 512GB SSD, ideal for professionals and creators',
                'prix' => 135000.00,
                'stock' => 5,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'HP Pavilion 15',
                'category' => 'laptop',
                'description' => 'Versatile 15.6" display, AMD Ryzen 7, 8GB RAM, 256GB SSD, perfect for everyday computing and entertainment',
                'prix' => 85000.00,
                'stock' => 8,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'MacBook Air M2',
                'category' => 'laptop',
                'description' => 'Powerful Apple Silicon M2, 8-core CPU, 10-core GPU, 8GB unified memory, 256GB SSD, incredible battery life',
                'prix' => 180000.00,
                'stock' => 3,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'ASUS VivoBook 14',
                'category' => 'laptop',
                'description' => 'Lightweight design, Intel Core i5, 8GB RAM, 512GB SSD, Full HD display, great for students and travelers',
                'prix' => 78000.00,
                'stock' => 10,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Lenovo ThinkPad E15',
                'category' => 'laptop',
                'description' => 'Business-grade laptop, Intel Core i5, 8GB RAM, 256GB SSD, MIL-STD-810H certified, secure and reliable',
                'prix' => 92000.00,
                'stock' => 7,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'MSI GE76 Raider',
                'category' => 'laptop',
                'description' => 'Gaming powerhouse, Intel Core i9, RTX 3080, 32GB RAM, 1TB SSD, 360Hz display for ultimate gaming',
                'prix' => 220000.00,
                'stock' => 2,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Acer Aspire 5',
                'category' => 'laptop',
                'description' => 'Mid-range performer, AMD Ryzen 5, 8GB RAM, 512GB SSD, large 15.6" display, excellent value for money',
                'prix' => 72000.00,
                'stock' => 12,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Razer Blade 14',
                'category' => 'laptop',
                'description' => 'Premium gaming laptop, Intel Core i7, RTX 4060, 16GB RAM, 512GB SSD, slim and powerful design',
                'prix' => 155000.00,
                'stock' => 4,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Surface Laptop 5',
                'category' => 'laptop',
                'description' => 'Microsoft\'s sleek design, Intel Core i7, 8GB RAM, 512GB SSD, touchscreen, premium build quality',
                'prix' => 148000.00,
                'stock' => 6,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'HP Envy x360',
                'category' => 'laptop',
                'description' => '2-in-1 convertible laptop, AMD Ryzen 7, 16GB RAM, 512GB SSD, touchscreen, versatile for work and play',
                'prix' => 125000.00,
                'stock' => 5,
                'image' => null,
                'images' => [],
            ],

            // ACCESSOIRES ET UNITÉS (10)
            [
                'nom' => 'Logitech MX Master 3S',
                'category' => 'unité',
                'description' => 'Advanced wireless mouse with precision scrolling, customizable buttons, optimal ergonomic design',
                'prix' => 8500.00,
                'stock' => 25,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Corsair K95 RGB Platinum',
                'category' => 'unité',
                'description' => 'Mechanical gaming keyboard, Cherry MX switches, aluminium frame, programmable macro keys',
                'prix' => 22000.00,
                'stock' => 8,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Samsung 27" 4K Monitor',
                'category' => 'unité',
                'description' => '4K resolution, 60Hz refresh rate, HDR support, USB-C connectivity, perfect for creative professionals',
                'prix' => 65000.00,
                'stock' => 6,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'SanDisk 1TB External SSD',
                'category' => 'unité',
                'description' => 'Portable solid state drive, 550MB/s read speed, compact design, password protected, durable',
                'prix' => 28000.00,
                'stock' => 15,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Sony WH-1000XM5 Headphones',
                'category' => 'unité',
                'description' => 'Premium wireless headphones, industry-leading noise cancellation, 30-hour battery, superior sound quality',
                'prix' => 42000.00,
                'stock' => 10,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Anker PowerBank 25000mAh',
                'category' => 'unité',
                'description' => 'High-capacity portable charger, dual USB-C ports, 65W fast charging, suitable for multiple devices',
                'prix' => 12000.00,
                'stock' => 30,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Razer DeathAdder V3',
                'category' => 'unité',
                'description' => 'Gaming mouse with 30,000 DPI sensor, 8 programmable buttons, lightweight design, RGB lighting',
                'prix' => 9500.00,
                'stock' => 18,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'ASUS ProArt PA278QV Monitor',
                'category' => 'unité',
                'description' => '27" IPS display, 99% sRGB coverage, hardware calibration, ideal for photo and video editing',
                'prix' => 58000.00,
                'stock' => 4,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Kingston Fury Beast 32GB RAM',
                'category' => 'unité',
                'description' => 'High-performance DDR4 memory, 3200MHz speed, CAS Latency 16, great for gaming and multitasking',
                'prix' => 8800.00,
                'stock' => 20,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Crucial P5 Plus 1TB NVMe',
                'category' => 'unité',
                'description' => 'High-speed NVMe SSD, 6600MB/s read speed, PCIe 4.0, excellent for system upgrades and storage expansion',
                'prix' => 11500.00,
                'stock' => 16,
                'image' => null,
                'images' => [],
            ],

            // IMPRIMANTES (10)
            [
                'nom' => 'Brother HL-L8360CDW',
                'category' => 'imprimante',
                'description' => 'Color laser printer, fast printing up to 33ppm, wireless and mobile printing, automatic 2-sided printing',
                'prix' => 48000.00,
                'stock' => 5,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Canon imagePROGRAF PRO-100',
                'category' => 'imprimante',
                'description' => 'Professional photo printer, 13.3" wide format, 10-color pigment ink system, exceptional image quality',
                'prix' => 85000.00,
                'stock' => 2,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'HP LaserJet Pro MFP M477fdw',
                'category' => 'imprimante',
                'description' => 'Multifunction laser printer, print/copy/scan/fax, color printing 28ppm, secure document handling',
                'prix' => 42000.00,
                'stock' => 6,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Xerox VersaLink B605',
                'category' => 'imprimante',
                'description' => 'Enterprise-grade multifunction printer, high volume output, advanced security features, reliable performance',
                'prix' => 95000.00,
                'stock' => 2,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Epson SureColor SC-P800',
                'category' => 'imprimante',
                'description' => 'Professional fine art printer, 17" maximum paper width, 10-color UltraChrome PRO ink, museum-quality prints',
                'prix' => 78000.00,
                'stock' => 3,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Ricoh MP C3004',
                'category' => 'imprimante',
                'description' => 'Multifunction color copier, 30ppm color and B/W, advanced finishing options, excellent for workgroups',
                'prix' => 120000.00,
                'stock' => 1,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'BrotherMFC-L9550CDW',
                'category' => 'imprimante',
                'description' => 'Professional color multifunction, fast printing 33ppm, 256MB memory, network and mobile connectivity',
                'prix' => 52000.00,
                'stock' => 4,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Canon imagePROGRAF TX-4100',
                'category' => 'imprimante',
                'description' => 'Innovative large format printer, 44" maximum width, 12-color ink system, automatic media detection',
                'prix' => 185000.00,
                'stock' => 1,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Konica Minolta bizhub C458',
                'category' => 'imprimante',
                'description' => 'Advanced multifunction system, 45ppm B/W and color, dynamic color replication, enhanced workflow',
                'prix' => 140000.00,
                'stock' => 1,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Brother HL-L2350DW',
                'category' => 'imprimante',
                'description' => 'Compact laser printer, 32ppm printing speed, automatic document feeder, wireless and mobile printing',
                'prix' => 28000.00,
                'stock' => 10,
                'image' => null,
                'images' => [],
            ],

            // MODEM ET ROUTEUR (10)
            [
                'nom' => 'ASUS RT-AX88U',
                'category' => 'modem',
                'description' => 'WiFi 6 router, 160MHz bandwidth support, 8 Gigabit ports, MU-MIMO technology, excellent gaming performance',
                'prix' => 38000.00,
                'stock' => 7,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'TP-Link Archer AX12',
                'category' => 'modem',
                'description' => 'WiFi 6 dual-band router, 4804Mbps total speed, OFDMA technology, 4x4 MU-MIMO, affordable high-speed option',
                'prix' => 18000.00,
                'stock' => 12,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Netgear Orbi Pro WiFi 6E',
                'category' => 'modem',
                'description' => 'Premium mesh WiFi 6E system, tri-band coverage, 10Gbps backhaul speed, professional-grade security',
                'prix' => 85000.00,
                'stock' => 3,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Motorola MB8600',
                'category' => 'modem',
                'description' => 'DOCSIS 3.1 cable modem, supports up to 32x8 channels, compatible with most cable providers, high-speed internet',
                'prix' => 22000.00,
                'stock' => 8,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Ubiquiti UniFi Dream Machine',
                'category' => 'modem',
                'description' => 'All-in-one network appliance with WiFi 6, 4-port Gigabit switch, advanced security, perfect for small businesses',
                'prix' => 58000.00,
                'stock' => 4,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'ASUS ZenWiFi AX6600',
                'category' => 'modem',
                'description' => 'Mesh WiFi system, dual-band coverage, AiMesh support for compatibility, parental controls and security features',
                'prix' => 28000.00,
                'stock' => 6,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Linksys Velop AXE300',
                'category' => 'modem',
                'description' => 'WiFi 6E mesh system, tri-band 12Gbps total speed, seamless coverage, intelligent routing technology',
                'prix' => 45000.00,
                'stock' => 5,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Arris SB8200',
                'category' => 'modem',
                'description' => 'DOCSIS 3.1 modem, supports gigabit speeds, multicast improvement, certified with major cable providers',
                'prix' => 18500.00,
                'stock' => 9,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'MikroTik hAP ax3',
                'category' => 'modem',
                'description' => 'WiFi 6 enterprise router, dual-band, RouterOS support for advanced configurations, excellent range',
                'prix' => 32000.00,
                'stock' => 5,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Eero Pro 6E',
                'category' => 'modem',
                'description' => 'WiFi 6E mesh system, 2.5Gbps port, Thread support for smart home, easy setup and management app',
                'prix' => 42000.00,
                'stock' => 6,
                'image' => null,
                'images' => [],
            ],

            // AUTRE (10)
            [
                'nom' => 'DJI Air 2S Drone',
                'category' => 'autre',
                'description' => '4K camera drone with 1" sensor, 31-minute flight time, obstacle detection, professional aerial photography',
                'prix' => 125000.00,
                'stock' => 2,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'GoPro Hero 11 Black',
                'category' => 'autre',
                'description' => '5.3K video recording, rugged waterproof design, advanced stabilization, perfect for action sports',
                'prix' => 52000.00,
                'stock' => 8,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Fujifilm X-T5 Camera',
                'category' => 'autre',
                'description' => 'Premium mirrorless camera, 40MP sensor, Fujifilm color film simulations, weather-sealed body, excellent ergonomics',
                'prix' => 185000.00,
                'stock' => 2,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Sony A6700 Camera',
                'category' => 'autre',
                'description' => 'Interchangeable lens camera, 32.4MP Exmor R CMOS sensor, advanced autofocus, 4K video at high frame rates',
                'prix' => 195000.00,
                'stock' => 1,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Meta Quest 3',
                'category' => 'autre',
                'description' => 'Advanced virtual reality headset, mixed reality capabilities, Snapdragon processor, vast library of games and apps',
                'prix' => 58000.00,
                'stock' => 5,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Nintendo Switch OLED',
                'category' => 'autre',
                'description' => 'Latest gaming console, OLED display, 64GB storage, versatile play modes, extensive game library',
                'prix' => 38000.00,
                'stock' => 10,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Apple iPad Pro 12.9',
                'category' => 'autre',
                'description' => 'Powerful tablet with M2 chip, ProMotion display, Apple Pencil support, ideal for creative professionals',
                'prix' => 95000.00,
                'stock' => 4,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Samsung Galaxy Tab S9 Ultra',
                'category' => 'autre',
                'description' => '14.6" tablet with Snapdragon 8 Gen 2, AMOLED display, S Pen included, excellent for productivity',
                'prix' => 82000.00,
                'stock' => 6,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Amazon Fire HD 10 Tablet',
                'category' => 'autre',
                'description' => '10.1" HD display, optimized for streaming, long battery life, affordable price, parental controls',
                'prix' => 22000.00,
                'stock' => 15,
                'image' => null,
                'images' => [],
            ],
            [
                'nom' => 'Anker Nebula Cosmos Max',
                'category' => 'autre',
                'description' => 'Premium projector, 1200 ANSI lumens, native 4K resolution, Android TV integrated, immersive home theater',
                'prix' => 68000.00,
                'stock' => 3,
                'image' => null,
                'images' => [],
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('50 produits créés avec succès!');
    }
}
